import view from './View/alias';
import button from './Button/alias';
import checkbox from './Checkbox/alias';
import checkboxGroup from './CheckboxGroup/alias';
import form from './Form/alias';
import input from './Input/alias';
import label from './Label/alias';
import scrollView from './ScrollView/alias';
import slider from './Slider/alias';
import switchComponent from './Switch/alias';
import textArea from './TextArea/alias';
import text from './Text/alias';
import icon from './Icon/alias';
import movableArea from './MovableArea/alias';
import movableView from './MovableView/alias';
import picker from './Picker/alias';
import pickerView from './PickerView/alias';
import pickerViewColumn from './PickerViewColumn/alias';
import progress from './Progress/alias';
import radio from './Radio/alias';
import radioGroup from './RadioGroup/alias';
import richText from './RichText/alias';
import swiper from './Swiper/alias';
import swiperItem from './SwiperItem/alias';
import block from './Block/alias';

export const aliasMap = new Map();
aliasMap.set('icon', icon);
aliasMap.set('movableArea', movableArea);
aliasMap.set('movableView', movableView);
aliasMap.set('picker', picker);
aliasMap.set('pickerView', pickerView);
aliasMap.set('pickerViewColumn', pickerViewColumn);
aliasMap.set('progress', progress);
aliasMap.set('radio', radio);
aliasMap.set('radioGroup', radioGroup);
aliasMap.set('richText', richText);
aliasMap.set('swiper', swiper);
aliasMap.set('swiperItem', swiperItem);
aliasMap.set('block', block);

aliasMap.set('view', view);
aliasMap.set('button', button);
aliasMap.set('checkbox', checkbox);
aliasMap.set('checkboxGroup', checkboxGroup);
aliasMap.set('form', form);
aliasMap.set('input', input);
aliasMap.set('label', label);
aliasMap.set('scrollView', scrollView);
aliasMap.set('slider', slider);
aliasMap.set('switch', switchComponent);
aliasMap.set('textarea', textArea);
aliasMap.set('text', text);
