import { BaseApis } from '@bytedance/mona'
// import formatPath from '../utils/formatPath';

const noImplementFactory = (api: string) => {
  return (): any => {
    console.error('no implement' + api + ' in web')
  };
}

class WebApis extends BaseApis {
  canIUse = noImplementFactory('canIUse')
  base64ToArrayBuffer = noImplementFactory('base64ToArrayBuffer')
  arrayBufferToBase64 = noImplementFactory('arrayBufferToBase64')
  getEnterOptionsSync = noImplementFactory('getEnterOptionsSync')
  getLaunchOptionsSync = noImplementFactory('getLaunchOptionsSync')
  exitMiniProgram = noImplementFactory('exitMiniProgram')
  canIPutStuffOverComponent = noImplementFactory('canIPutStuffOverComponent')
  getUpdateManager = noImplementFactory('getUpdateManager')
  onAppShow = noImplementFactory('onAppShow')
  offAppShow = noImplementFactory('offAppShow')
  onAppHide = noImplementFactory('onAppHide')
  offAppHide = noImplementFactory('offAppHide')
  onError = noImplementFactory('onError')
  offError = noImplementFactory('offError')
  env = {
    VERSION: '1',
    USER_DATA_PATH: '/'
  }
  downloadFile = noImplementFactory('downloadFile')
  request = noImplementFactory('request')
  uploadFile = noImplementFactory('uploadFile')
  connectSocket = noImplementFactory('connectSocket')
  chooseImage = noImplementFactory('chooseImage')
  saveImageToPhotosAlbum = noImplementFactory('saveImageToPhotosAlbum')
  previewImage = noImplementFactory('previewImage')
  getImageInfo = noImplementFactory('getImageInfo')
  compressImage = noImplementFactory('compressImage')
  getRecorderManager = noImplementFactory('getRecorderManager')
  getBackgroundAudioManager = noImplementFactory('getBackgroundAudioManager')
  createInnerAudioContext = noImplementFactory('createInnerAudioContext')
  chooseVideo = noImplementFactory('chooseVideo')
  saveVideoToPhotoAlbum = noImplementFactory('saveVideoToPhotoAlbum')
  createVideoContext = noImplementFactory('createVideoContext')
  craeteLivePlayerContext = noImplementFactory('craeteLivePlayerContext')
  preloadVideo = noImplementFactory('preloadVideo')
  createCameraContext = noImplementFactory('createCameraContext')
  createEffectCameraStream = noImplementFactory('createEffectCameraStream')
  createMapContext = noImplementFactory('createMapContext')
  saveFile = noImplementFactory('saveFile')
  getFileInfo = noImplementFactory('getFileInfo')
  getSavedFileList = noImplementFactory('getSavedFileList')
  openDocument = noImplementFactory('openDocument')
  removeSavedFile = noImplementFactory('removeSavedFile')
  getFileSystemManager = noImplementFactory('getFileSystemManager')
  getEnvInfoSync = noImplementFactory('getEnvInfoSync')
  login = noImplementFactory('login')
  checkSession = noImplementFactory('checkSession')
  getUserInfo = noImplementFactory('getUserInfo')
  getUserInfoProfile = noImplementFactory('getUserInfoProfile')
  createRewardedVideoAd = noImplementFactory('createRewardedVideoAd')
  createInterstitialAd = noImplementFactory('createInterstitialAd')
  pay = noImplementFactory('pay')
  navigateToMiniProgram = noImplementFactory('navigateToMiniProgram')
  navigateBackMiniProgram = noImplementFactory('navigateBackMiniProgram')
  chooseAddresses = noImplementFactory('chooseAddresses')
  getSetting = noImplementFactory('getSetting')
  openSettings = noImplementFactory('openSettings')
  authorize = noImplementFactory('authorize')
  showDouyinOpenAuth = noImplementFactory('showDouyinOpenAuth')
  reportAnalytics = noImplementFactory('reportAnalytics')
  canRateAwemeOrders = noImplementFactory('canRateAwemeOrders')
  rateAwemeOrder = noImplementFactory('rateAwemeOrder')
  followOfficialAccount = noImplementFactory('followOfficialAccount')
  checkFollowState = noImplementFactory('checkFollowState')
  openAwemeUserProfile = noImplementFactory('openAwemeUserProfile')
  followAwemeUser = noImplementFactory('followAwemeUser')
  requestSubscribeMessage = noImplementFactory('requestSubscribeMessage')
  openDouyinOrderList = noImplementFactory('openDouyinOrderList')
  openEcGood = noImplementFactory('openEcGood')
  openEcOrderDetail = noImplementFactory('openEcOrderDetail')
  openEcIm = noImplementFactory('openEcIm')
  openEcChat = noImplementFactory('openEcChat')
  openWebcastRoom = noImplementFactory('openWebcastRoom')
  openDouyinProfile = noImplementFactory('openDouyinProfile')
  openEcCoupon = noImplementFactory('openEcCoupon')
  performance = {
    getEntries: noImplementFactory('getEntries'),
    getEntriesByName: noImplementFactory('getEntriesByName'),
    getEntriesByType: noImplementFactory('getEntriesByType'),
    getCurrentPageEntries: noImplementFactory('getCurrentPageEntries'),
    getEntriesByPage: noImplementFactory('getEntriesByPage'),
    mark: noImplementFactory('mark'),
    clearMarks: noImplementFactory('clearnMarks'),
  }
  getStorage = noImplementFactory('getStorage')
  getStorageSync = noImplementFactory('getStorageSync')
  setStorage = noImplementFactory('setStorage')
  setStorageSync = noImplementFactory('setStorageSync')
  removeStorage = noImplementFactory('removeStorage')
  removeStorageSync = noImplementFactory('removeStorageSync')
  clearStorage = noImplementFactory('clearStorage')
  clearStorageSync = noImplementFactory('clearStorageSync')
  getStorageInfo = noImplementFactory('getStorageInfo')
  getStorageInfoSync = noImplementFactory('getStorageInfoSync')
  getLocation = noImplementFactory('getLocation')
  chooseLocation = noImplementFactory('chooseLocation')
  openLocation = noImplementFactory('openLocation')
  getNetworkType = noImplementFactory('getNetworkType')
  onNetworkStatusChange = noImplementFactory('onNetworkStatusChange')
  getWifiList = noImplementFactory('getWifiList')
  onGetWifiList = noImplementFactory('onGetWifiList')
  offGetWifiList = noImplementFactory('offGetWifiList')
  getSystemInfo = noImplementFactory('getSystemInfo')
  getSystemInfoSync = noImplementFactory('getSystemInfoSync')
  getConnectedWifi = noImplementFactory('getConnectedWifi')
  startAccelerometer = noImplementFactory('startAccelerometer')
  stopAccelerometer = noImplementFactory('stopAccelerometer')
  onAccelerometerChange = noImplementFactory('onAccelerometerChange')
  startCompass = noImplementFactory('startCompass')
  stopCompass = noImplementFactory('stopCompass')
  onCompassChange = noImplementFactory('onCompassChange')
  makePhoneCall = noImplementFactory('makePhoneCall')
  scanCode = noImplementFactory('scanCode')
  getClipboardData = noImplementFactory('getClipboardData')
  setClipboardData = noImplementFactory('setClipboardData')
  setKeepScreenOn = noImplementFactory('setKeepScreenOn')
  onUserCaptureScreen = noImplementFactory('onUserCaptureScreen')
  offUserCaptureScreen = noImplementFactory('offUserCaptureScreen')
  getScreenBrightness = noImplementFactory('getScreenBrightness')
  setScreenBrightness = noImplementFactory('setScreenBrightness')
  disableUserScreenRecord = noImplementFactory('disableUserScreenRecord')
  enableUserScreenRecord = noImplementFactory('enableUserScreenRecord')
  onUserScreenRecord = noImplementFactory('onUserScreenRecord')
  offUserScreenRecord = noImplementFactory('offUserScreenRecord')
  vibrateShort = noImplementFactory('vibrateShort')
  vibrateLong = noImplementFactory('vibrateLong')
  onMemoryWarning = noImplementFactory('onMemoryWarning')
  createCanvasContext = noImplementFactory('createCanvasContext')
  createOffscreenCanvas = noImplementFactory('createOffscreenCanvas')
  showToast = noImplementFactory('showToast')
  hideToast = noImplementFactory('hideToast')
  showLoading = noImplementFactory('showLoading')
  hideLoading = noImplementFactory('hideLoading')
  showModal = noImplementFactory('showModal')
  showActionSheet = noImplementFactory('showActionSheet')
  showFavoriteGuide = noImplementFactory('showFavoriteGuide')
  showInteractionBar = noImplementFactory('showInteractionBar')
  hideInteractionBar = noImplementFactory('hideInteractionBar')
  showNavigationBarLoading = noImplementFactory('showNavigationBarLoading')
  hideNavigationBarLoading = noImplementFactory('hideNavigationBarLoading')
  hideHomeButton = noImplementFactory('hideHomeButton')
  setNavigationBarTitle = noImplementFactory('setNavigationBarTitle')
  setNavigationBarColor = noImplementFactory('setNavigationBarColor')
  getMenuButtonBoundingClientRect = noImplementFactory('getMenuButtonBoundingClientRect')
  createAnimation = noImplementFactory('createAnimation')
  pageScrollTo = noImplementFactory('pageScrollTo')
  setSwipeBackMode = noImplementFactory('setSwipeBackMode')
  startPullDownRefresh = noImplementFactory('startPullDownRefresh')
  showTabBarRedDot = noImplementFactory('showTabBarRedDot')
  showTabBar = noImplementFactory('showTabBar')
  setTabBarStyle = noImplementFactory('setTabBarStyle')
  setTabBarItem = noImplementFactory('setTabBarItem')
  setTabBarBadge = noImplementFactory('setTabBarBadge')
  removeTabBarBadge = noImplementFactory('removeTabBarBadge')
  hideTabBarRedDot = noImplementFactory('hideTabBarRedDot')
  hideTabBar = noImplementFactory('hideTabBar')
  getAlgorithmManager = noImplementFactory('getAlgorithmManager')
  createStickerManager = noImplementFactory('createStickerManager')
  createBytennEngineContext = noImplementFactory('createBytennEngineContext')
  navigateTo = noImplementFactory('navigateTo')
  redirectTo = noImplementFactory('redirectTo')
  switchTab = noImplementFactory('switchTab')
  navigateBack = noImplementFactory('navigateBack')
  reLaunch = noImplementFactory('reLaunch')
  showShareMenu = noImplementFactory('showShareMenu')
  hideShareMenu = noImplementFactory('hideShareMenu')
  navigateToVideoView = noImplementFactory('navigateToVideoView')
  getExtConfig = noImplementFactory('getExtConfig')
  getExtConfigSync = noImplementFactory('getExtConfigSync')
  createSelectorQuery = noImplementFactory('createSelectorQuery')
  createIntersectionObserver = noImplementFactory('createIntersectionObserver')
  createLiveReportContext = noImplementFactory('createLiveReportContext')
  getRoomInfo = noImplementFactory('getRoomInfo')
  getLiveUserInfo = noImplementFactory('getLiveUserInfo')
  getSelfCommentCountDuringPluginRunning = noImplementFactory('getSelfCommentCountDuringPluginRunning')
  isFollowingAnchor = noImplementFactory('isFollowingAnchor')
  onReceiveAudiencesFollowAction = noImplementFactory('onReceiveAudiencesFollowAction')
  subscribeAudiencesFollowAction = noImplementFactory('subscribeAudiencesFollowAction')
  unsubscribeAudiencesFollowAction = noImplementFactory('unsubscribeAudiencesFollowAction')
  subscribeSpecifiedContentComment = noImplementFactory('subscribeSpecifiedContentComment')
  subscribeSpecifiedUserComment = noImplementFactory('subscribeSpecifiedUserComment')
  unsubscribeAllSpecifiedContentComment = noImplementFactory('unsubscribeAllSpecifiedContentComment')
  unsubscribeAllSpecifiedUserComment = noImplementFactory('unsubscribeAllSpecifiedUserComment')
  onReceiveSpecifiedComment = noImplementFactory('onReceiveSpecifiedComment')
  open = noImplementFactory('open')
}

export default WebApis