name: publish mona packages
# build
# test
# publish
on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: "build mona packages"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.18.0'
      - name: Install Dependencies
        run: yarn

