name: Mona Test
on:
  push:
    branches:
      - main
      - feat/coverage

  pull_request:
    branches:
      - main

jobs:
  testCoverage:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.18.0]
    steps:
      # prepare env
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: update
        run: |
          sudo apt update

      - name: install packages
        run: |
          yarn config set registry http://registry.npmjs.org
          yarn

      - name: build
        run: |
          yarn global add lerna@4.0.0
          lerna run build

      - name: test
        run: |
          yarn test

      - name: install codecov
        run: yarn global add codecov

      - name: Install requirements
        run: codecov --token=${{ secrets.CODECOV_TOKEN }}
comment: # this is a top-level key
  layout: 'reach, diff, flags, files'
  behavior: default
  require_changes: false # if true: only post the comment if coverage changes
  require_base: no # [yes :: must have a base report to post]
  require_head: yes # [yes :: must have a head report to post]
