name: Mona Test
on:
  push:
    branches:
      - main
      - feat/coverage

  pull_request:
    branches:
      - main
      - feat/coverage
      - feat/coverage2

jobs:
  testCoverage:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.18.0]
    steps:
      # prepare env
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: update
        run: |
          sudo apt update

      - name: install codecov
        run: yarn global add codecov

      - name: Install requirements
        run: codecov --token=${{ secrets.CODECOV_TOKEN }}
      - name: Upload coverage report
        uses: codecov/codecov-action@v2
