name: Mona Version
on:
  push:
    branches:
      - 'publish/*'

jobs:
  version:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.18.0]

    steps:
      # prepare env
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Release Branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name:

      - name: Get Version
        run: |
          TEMP=`echo "${{ github.ref }}"`
          CURRNET_VERSION=`echo ${TEMP:19}`
          TAG=`echo ${CURRNET_VERSION} | egrep -o "[a-zA-Z]+"`
          TAG="${TAG:-latest}"
          echo "cversion=${CURRNET_VERSION}" >> $GITHUB_ENV
          echo "ctag=${TAG}" >> $GITHUB_ENV

        # install node
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: ${{ matrix.node-version }}

      - name: Install Lerna
        run: yarn global add lerna@4.0.0 -W

      # - name: Install Dependencies
      #   run: yarn

      # - name: run test
      #   run: yarn test
      - name: Create New Branch
        run: |
          git checkout -b release/${{ env.cversion }}
          git push --set-upstream origin release/${{ env.cversion }}

      - name: Change Version
        run: |
          lerna version ${{ env.cversion }} --exact --no-git-tag-version --force-publish --yes
          git status

      - name: Commit And Push
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GH_PAT }}
          message: 'chore(release): publish version ${{ env.cversion }} --tag=${{ env.ctag }}'
          branch: 'release/${{ env.cversion }}'

      - name: Delete Publish Branch
        run: |
          git push origin -d publish/${{ env.cversion }}
