name: Mona Version
on:
  push:
    branches:
      - 'publish/*'

jobs:
  version:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.18.0]

    steps:
      # prepare env
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Get Version
        run: |
          TEMP=`echo "${{ github.ref }}"`
          CURRNET_VERSION=`echo ${TEMP:19}`
          TAG=`echo ${CURRNET_VERSION} | egrep -o "[a-zA-Z]+"`
          TAG="${TAG:-latest}"
          echo "cversion=${CURRNET_VERSION}" >> $GITHUB_ENV
          echo "ctag=${TAG}" >> $GITHUB_ENV

        # install node
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: ${{ matrix.node-version }}

      - name: Install Lerna
        run: yarn global add lerna@4.0.0 -W

      - name: Install Dependencies
        run: yarn

      - name: Build Packages
        run: lerna run build

      - name: Auto Test
        run: yarn test

      - name: Change Version
        run: |
          git checkout -b release/${{ env.cversion }}
          lerna version ${{ env.cversion }} --exact --no-git-tag-version --force-publish --yes
          git status

      - name: Commit And Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore(release): publish version ${{ env.cversion }} --tag=${{ env.ctag }}'
          branch: 'release/${{ env.cversion }}'
          create_branch: true

      - name: Delete Publish Branch
        if: always()
        run: |
          git push origin -d publish/${{ env.cversion }}
