export const nodeMap: { [key: string]: string[] } = {
  a: [],
  abbr: [],
  address: [],
  article: [],
  aside: [],
  b: [],
  bdi: [],
  bdo: ['dir'],
  big: [],
  blockquote: [],
  br: [],
  caption: [],
  center: [],
  cite: [],
  code: [],
  col: ['span', 'width'],
  colgroup: ['span', 'width'],
  dd: [],
  del: [],
  div: [],
  dl: [],
  dt: [],
  em: [],
  fieldset: [],
  font: [],
  footer: [],
  h1: [],
  h2: [],
  h3: [],
  h4: [],
  h5: [],
  h6: [],
  header: [],
  hr: [],
  i: [],
  img: ['alt', 'src', 'height', 'width'],
  ins: [],
  label: [],
  legend: [],
  li: [],
  mark: [],
  nav: [],
  ol: ['start', 'type'],
  p: [],
  pre: [],
  q: [],
  rt: [],
  ruby: [],
  s: [],
  section: [],
  small: [],
  span: [],
  strong: [],
  sub: [],
  sup: [],
  table: ['width'],
  tbody: [],
  td: ['colspan', 'height', 'rowspan', 'width'],
  tfoot: [],
  th: ['colspan', 'height', 'rowspan', 'width'],
  thead: [],
  tr: ['colspan', 'height', 'rowspan', 'width'],
  tt: [],
  u: [],
  ul: [],
  video: ['src', 'poster'],
}